nginx:
  build: ./nginx/
  container_name: nginx-lemp
  ports:
    - 8080:80
    - 443:443
  links:
    - php
  volumes:
    - ./src/:/var/www/html

php:
  build: ./php/
  container_name: php-lemp
  expose:
    - 9000
  links:
    - mysql
  volumes:
    - ./src/:/var/www/html

mysql:
  build: ./mysql/
  container_name: mysql-lemp
  ports:
    - 3306:3306
  volumes:
    - ./mysql/data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: rootPass
    MYSQL_DATABASE: db
    MYSQL_USER: userdb
    MYSQL_PASSWORD: userPass